# Generated by Django 4.0.4 on 2022-04-30 16:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('work_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('min_pay', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mainuser')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.mainuser')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('service_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mainuser')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.servicetypes')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bidder_msg', models.TextField()),
                ('bid_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(max_length=64)),
                ('bidder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mainuser')),
                ('workoffer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workoffer')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('client_msg', models.TextField()),
                ('status', models.CharField(max_length=64)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mainuser')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service')),
            ],
        ),
    ]
