# Generated by Django 4.0.4 on 2022-05-01 05:52

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='avatar',
            field=models.ImageField(default='user/avatar.jpg', upload_to=dashboard.models.user_directory_path),
        ),
    ]
