# Generated by Django 4.0.4 on 2022-05-14 14:59

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_mainuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='avatar',
            field=models.ImageField(default='users/avatar.png', upload_to=dashboard.models.user_directory_path),
        ),
    ]
