# Generated by Django 4.0.4 on 2022-05-15 06:45

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_mainuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoffer',
            name='thumbnail',
            field=models.ImageField(default='workoffers/default.png', upload_to=dashboard.models.workoffer_directory_path),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='status',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
