# Generated by Django 4.0.4 on 2022-05-16 02:49

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_workoffer_thumbnail_alter_workoffer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetypes',
            name='tag',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dashboard.models.service_directory_path)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service')),
            ],
        ),
    ]
