# Generated by Django 4.0.4 on 2022-05-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_workoffer_thumbnail_workofferimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveService',
            new_name='ServiceClients',
        ),
    ]
