# Generated by Django 4.0.4 on 2022-05-24 09:37

import dashboard.custom_models.compressed_image_field
import dashboard.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_activeservice_serviceclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('message', models.TextField()),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.serviceclients')),
            ],
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='avatar',
            field=dashboard.custom_models.compressed_image_field.CompressedImageField(default='users/avatar.png', quality=60, upload_to=dashboard.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=dashboard.custom_models.compressed_image_field.CompressedImageField(quality=70, upload_to=dashboard.models.service_directory_path),
        ),
        migrations.AlterField(
            model_name='workofferimage',
            name='image',
            field=dashboard.custom_models.compressed_image_field.CompressedImageField(quality=60, upload_to=dashboard.models.workoffer_directory_path),
        ),
        migrations.CreateModel(
            name='ServiceReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', dashboard.custom_models.compressed_image_field.CompressedImageField(quality=60, upload_to=dashboard.models.service_review_directory_path)),
                ('service_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.servicereview')),
            ],
        ),
    ]
