# Generated by Django 4.0.4 on 2022-05-25 13:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_mainuser_avatar_alter_serviceimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
