# Generated by Django 4.0.4 on 2022-05-25 14:47

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_mainuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
    ]
