# Generated by Django 4.0.4 on 2022-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_mainuser_city_alter_mainuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='locality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='sublocality',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
