# Generated by Django 4.0.4 on 2022-05-30 17:00

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_mainuser_full_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='full_addr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='locality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='14.572950835033037,480.992431640625', max_length=63),
        ),
        migrations.AddField(
            model_name='service',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='sublocality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
